version: 1.0.{build}
image: Visual Studio 2019

matrix:
  fast_finish: false

environment:
 BUILD_CYTOLK: 1
 TWINE_PASSWORD:
  secure: rkuAw6G/Ep2MvjqPTTu95A==
 matrix:
  - cI_ARCHITECTURE: 32

  - CI_ARCHITECTURE: 64

install:
 - git submodule update --init --recursive

build_script:
- ps: .\ci\build_python.ps1
- ps: './ci/release.ps1'

artifacts:
- path: dist\*

deploy:
  - provider: GitHub
    auth_token:
     secure: PkV3IlJTs1RbIvBp7F3sYU45MyO6RkfpHDBA696eHV7Jgrt+dNjqWcl/IeNBTIEa
    on:
      branch: master
      APPVEYOR_REPO_TAG: true