on:
  push: {}

jobs:
  build:
    runs-on: windows-2019
    env:
      CI_ARCH: ${{ matrix.CI_ARCH }}
      PYVERSION: ${{matrix.PYVERSION}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: build wheels
        shell: powershell
        run: |
          set-location $Env:GITHUB_WORKSPACE
          ./ci\build_python.ps1
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cytolk-win${{matrix.CI_ARCH}}-${{matrix.PYVERSION}}
          path: dist/*
    strategy:
      fail-fast: true
      matrix:
        CI_ARCH: ["32", "64"]
        PYVERSION: ["3.10", "3.9", "3.8", "3.7", "3.6"]