on:
  push: {}

jobs:
  build:
    runs-on: windows-2019
    env:
      CI_ARCH: ${{ matrix.CI_ARCH }}
      BUILD_CYTOLK: "1"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: get python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.PYVERSION}}
      - run: pip install cython setuptools wheel && python setup.py bdist_wheel
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cytolk-py${{matrix.PYVERSION}}-${{matrix.CI_ARCH}}
          path: dist/*
    strategy:
      fail-fast: true
      matrix:
        CI_ARCH: ["x86", "x64"]
        PYVERSION: ["3.10", "3.9", "3.8", "3.7", "3.6"]

  deploy:
    needs: ["build"]
    runs-on: ubuntu-20.04
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{matrix.ARTIFACT}}
          path: /dist
      - name: upload to test pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{secrets.TEST_PYPI_TOKEN}}
          repository_url: https://test.pypi.org/legacy/
      - name: Upload to Pypi
        if: startsWith(github.ref, 'refs/tags') && !github.event_type != 'pull_request'    
        env:
          TWINE_USERNAME: pauliyobo
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
        run: |
          sudo pip3 install twine
          twine upload /home/runner/artifacts/*
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        ARTIFACT:
          - cytolk-py3.10-x86
          - cytolk-py3.10-x64
          - cytolk-py3.9-x86
          - cytolk-py3.9-x64
          - cytolk-py3.8-x86
          - cytolk-py3.8-x64
          - cytolk-py3.7-x86
          - cytolk-py3.7-x64
          - cytolk-py3.6-x86
          - cytolk-py3.6-x64
