on:
  push: {}

jobs:
  build:
    runs-on: windows-2019
    env:
      CI_ARCH: ${{ matrix.CI_ARCH }}
      BUILD_CYTOLK: "1"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: get python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYVERSION}}
          architecture: ${{ matrix.CI_ARCH }}
      - run: pip install cython setuptools wheel && python setup.py bdist_wheel
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cytolk-py${{matrix.PYVERSION}}-${{matrix.CI_ARCH}}
          path: dist/*
    strategy:
      fail-fast: true
      matrix:
        CI_ARCH: ["x86", "x64"]
        PYVERSION: ["3.12", "3.11", "3.10", "3.9", "3.8"]

  deploy:
    needs: ["build"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ~/artifacts
      - shell: bash
        run: cd /home/runner/artifacts && ls
      - name: Upload to Pypi
        if: startsWith(github.ref, 'refs/tags') && !github.event_type != 'pull_request' && github.ref_name != 'test'
        env:
          TWINE_USERNAME: pauliyobo
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
        run: |
          sudo pip3 install twine
          twine upload /home/runner/artifacts/**/*.whl
      - name: Release on github
        if: startsWith(github.ref, 'refs/tags') && !github.event_type != 'pull_request'    
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/runner/artifacts/**/*.whl"
          generateReleaseNotes: true
          draft: true
