on:
  push: {}

jobs:
  build:
    runs-on: windows-2019
    env:
      CI_ARCH: ${{ matrix.CI_ARCH }}
      BUILD_CYTOLK: "1"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: build wheels
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.PYVERSION}}
        run: |
          pip install cython setuptools wheel
          py setup.py bdist_wheel
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cytolk-win${{matrix.CI_ARCH}}-${{matrix.PYVERSION}}
          path: dist/*
    strategy:
      fail-fast: true
      matrix:
        CI_ARCH: ["x86", "x64"]
        PYVERSION: ["3.10", "3.9", "3.8", "3.7", "3.6"]
